apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: investment-api-ingress
  namespace: investment
  annotations:
    # Tell AWS to build an Application Load Balancer
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
    # Open both ports and attach your certificate
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:620173787208:certificate/db734853-f660-47c7-9be8-574bf43f798e"
    
    # The magic redirect rule
    alb.ingress.kubernetes.io/ssl-redirect: '443'

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: investment-api-public
                port:
                  number: 80