apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: investment-api-ingress
  namespace: investment
  annotations:
    kubernetes.io/ingress.class: alb
    # internet-facing for demo; change to "internal" for real internal tools
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: investment-api
                port:
                  number: 80
