apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

# 1. Real ECR URL to prevent ImagePullBackOff
images:
  - name: investment-api
    newName: 620173787208.dkr.ecr.us-east-1.amazonaws.com/investment-assistant-api
    newTag: latest