apiVersion: v1
kind: ConfigMap
metadata:
  name: investment-api-config
  namespace: investment
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "investment-assistant-data"
  LLM_PROVIDER: "openai"
  # --- Airflow SQLite Settings ---
  AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  # AIRFLOW__CORE__FERNET_KEY: "GenerateAFernetKeyAndPutItHere"

