apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit everything from base
resources:
  - ../../base

# Override image to local docker build
images:
  - name: investment-api
    newName: investment-api
    newTag: dev

# Scale down for local development
patches:
  - target:
      kind: Deployment
      name: investment-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: ConfigMap
      name: investment-api-config
    patch: |
      - op: replace
        path: /data/APP_ENV
        value: development
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
